# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codescript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codescript',
            name='banner',
        ),
        migrations.AlterField(
            model_name='codescript',
            name='css_file_path',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codescript',
            name='html_file_path',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codescript',
            name='js_file_path',
            field=models.TextField(max_length=255),
        ),
    ]
